name: CI / Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r dev_requirements.txt
      
      # Create a valid config.ini so viewport.py import passes
      - name: Write out config.ini
        run: |
          cat << 'EOF' > config.ini
          [General]
          SLEEP_TIME = 300
          WAIT_TIME = 30
          MAX_RETRIES = 5

          [Logging]
          LOG_FILE = true
          LOG_CONSOLE = true
          DEBUG_LOGGING=False
          ERROR_LOGGING = false
          LOG_DAYS = 7
          LOG_INTERVAL = 60

          [API]
          USE_API = false
          EOF

      # Create a minimal .env so viewport.py import passes
      - name: Write out .env
        run: |
          cat << 'EOF' > .env
          USERNAME=testuser
          PASSWORD=testpass
          URL=http://example.com
          EOF

      - name: Run tests
        run: pytest --cov --cov-branch --cov-report=xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true