name: Sync snapshot on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout snapshot branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: snapshot

      - name: Merge main into snapshot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git merge --no-ff origin/main -m "Merge Main → Snapshot"

      - name: Replace Badges and Add SNAPSHOT Warning
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const file = 'README.md';
            let md = fs.readFileSync(file,'utf8');
            const warning = `# SNAPSHOT
            You are currently seeing the snapshot branch. This is where I make rapid changes and experiment with new code. If this branch is ahead of main, it is most likely broken. 
            Check the [latest release](https://github.com/Samuel1698/fakeViewport/releases) or go to [main](https://github.com/Samuel1698/fakeViewport/tree/main) for a stable version of the code.

            ---
            
            `;

            const badges = `
            [![Python](https://github.com/Samuel1698/fakeViewport/actions/workflows/python-test.yml/badge.svg?branch=snapshot)](https://github.com/Samuel1698/fakeViewport/actions/workflows/python-test.yml)
            `;

            const regionRe = /<!-- \[START BADGES\] -->[\s\S]*?<!-- \[END BADGES\] -->/gm;
              md = md.replace(
                regionRe,
                `<!-- [START BADGES] -->\n${badges}\n<!-- [END BADGES] -->`
              );
            
            if (!md.includes('# SNAPSHOT')) {
              const endBadges = '<!-- [END BADGES] -->';
              const parts = md.split(endBadges);
              if (parts.length >= 2) {
                md = parts[0] + endBadges + '\n\n' + warning + parts[1];
              }
            }

            fs.writeFileSync(file, md);

      - name: Commit & push snapshot updates
        run: |
          git add README.md
          git commit -m "Update README" || echo "No changes to commit"
          git push origin snapshot
